apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: fongjemaine/consumer5
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
          
  
---
apiVersion: v1
kind: Service
metadata:
  name: consumer
spec:
  type: NodePort
  selector:
    app: consumer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 33225